variables:
  - &buildx-plugin 'woodpeckerci/plugin-docker-buildx:5.1.0'
  - &repo 'woodpeckerci/plugin-surge-preview'
  - &platforms 'linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le'

steps:
  dryrun:
    image: *buildx-plugin
    settings:
      dry_run: true
      repo: *repo
      platforms: *platforms
      tag: test
    when:
      event: pull_request

  publish-next:
    image: *buildx-plugin
    settings:
      repo: *repo
      platforms: *platforms
      tag: next
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  publish-tag:
    image: *buildx-plugin
    settings:
      repo: *repo
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG}"]
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      event: tag
